version: "3"

services:
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --prefer-dist --no-progress
  database:
    container_name: postgres
    restart: always
    image: postgres:14.5
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: "flight_notifier"
      POSTGRES_PASSWORD: "root"